set(TDTWAVETOMO wavetomo)
ExternalProject_Add(${TDTWAVETOMO}
    GIT_REPOSITORY git@github.com:rhyshawkins/TDTWavetomo2D.git
    GIT_SHALLOW ON
    GIT_SUBMODULES ""
    UPDATE_COMMAND ""
    CONFIGURE_COMMAND ""
    BUILD_COMMAND make TDTBASE=${TDTBASE_SRC} TRAVELTIMEBASE=${TRAVELTIME_SRC} CXX=${CMAKE_CXX_COMPILER}
    BUILD_IN_SOURCE ON
    INSTALL_COMMAND ""
    DEPENDS ${TRAVELTIME}
)
ExternalProject_Get_Property(${TDTWAVETOMO} SOURCE_DIR)
set(TDTWAVETOMO_INCLUDE ${SOURCE_DIR})