name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  BUILD_TYPE: Debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Cmake buid and test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          brew install gsl fftw
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: >-
          cmake $GITHUB_WORKSPACE
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCMAKE_CXX_FLAGS=-I\ /usr/local/include

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Build dummy prior file for tests
        run: |
          echo laplace >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.2 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo priorbirth >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo depthgaussianperturb >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 7 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.020 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.020 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.025 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.035 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.050 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.050 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt
          echo 0.050 >> ${{runner.workspace}}/build/tests/tutorial_prior.txt

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C $BUILD_TYPE -T test --output-on-failure
