name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  BUILD_TYPE: Debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Cmake buid and test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: >-
          cmake $GITHUB_WORKSPACE
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_CXX_COMPILER=mpicxx
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C $BUILD_TYPE
