name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  BUILD_TYPE: Debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Cmake buid and test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          brew install gsl fftw
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: >-
          cmake $GITHUB_WORKSPACE
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCMAKE_CXX_FLAGS=-I\ /usr/local/include

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - uses: DamianReeves/write-file-action
        with:
          path: ${{runner.workspace}}/build/tutorial_prior.txt
          contents: |
            laplace
            0.2
            priorbirth
            depthgaussianperturb
            7
            0.020
            0.020
            0.025
            0.035
            0.050
            0.050
            0.050
          write-mode: append

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C $BUILD_TYPE -T test --output-on-failure
